import express from 'express';
const router = express.Router();
import userRoutes from './user.routes.js';
import productRoutes from './product.routes.js';
import orderProductRoutes from './orderProduct.routes.js';
import businessRoutes from './business.routes.js';
import orderRoutes from './order.routes.js';
import orderTrackRoutes from './orderTrack.routes.js';
import serviceRoutes from './services.routes.js';
import orderServiceRoutes from './orderService.routes.js';
import customerRoutes from './customer.routes.js';
import productCategoryRoutes from './routes/productCategory.routes.js';
import orderStatusRoutes from './routes/orderStatus.routes.js';
import businessUserRoleRoutes from './routes/businessUserRole.routes.js';
import businessUserRoutes from './routes/businessUser.routes.js';
import userTypeRoutes from './routes/userType.routes.js';
import employeeRoutes from './employee.routes.js';

router.use('/users', userRoutes);
router.use('/products', productRoutes);
router.use('/orderProducts', orderProductRoutes);
router.use('/business', businessRoutes);
router.use('/orders', orderRoutes);
router.use('/orderTracks', orderTrackRoutes);
router.use('/services', serviceRoutes);
router.use('/orderServices', orderServiceRoutes);
router.use('/customers', customerRoutes);
router.use('/productsCategory', productCategoryRoutes);
router.use('/ordersStatus', orderStatusRoutes);
router.use('/businessUserRole', businessUserRoleRoutes);
router.use('/businessUsers', businessUserRoutes);
router.use('/userTypes', userTypeRoutes);
router.use('/employees', employeeRoutes);

export default router;